# Generated by Django 6.0.5 on 2026-07-13 11:17

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', store.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PAY_ON_DELIVERY', 'Pay on Delivery'), ('MTN_MOBILE_MONEY', 'MTN Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('BANK_TRANSFER', 'Bank Transfer')], default='PAY_ON_DELIVERY', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Converted', 'Converted'), ('Expired', 'Expired')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_carts', to='store.customer'),
        ),
    ]
