# Generated by Django 6.0.5 on 2026-08-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_user_role_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_4',
            field=models.URLField(blank=True, null=True),
        ),
    ]
