# Generated by Django 6.0.5 on 2026-09-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_image_url_2_product_image_url_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, default='broadcast', max_length=100, null=True),
        ),
    ]
