"""
Django settings for backend project.

Generated by 'django-admin startproject'.
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def sanitize_env_value(value: str | None) -> str:
    if value is None:
        return ''
    cleaned = value.strip().replace('\r', '')
    if '\n' in cleaned:
        cleaned = cleaned.split('\n', 1)[0].strip()
    return cleaned.strip('"').strip("'")


def load_environment_file(env_path: Path) -> None:
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = sanitize_env_value(value)
        os.environ[key] = value


def get_bool_env(key: str, default: bool = False) -> bool:
    value = os.getenv(key)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def resolve_email_backend() -> str:
    configured_backend = sanitize_env_value(os.getenv('EMAIL_BACKEND'))
    if configured_backend and configured_backend.startswith('django.core.mail.backends.'):
        return configured_backend

    if os.getenv('EMAIL_HOST_USER') and os.getenv('EMAIL_HOST_PASSWORD'):
        return 'django.core.mail.backends.smtp.EmailBackend'

    return 'django.core.mail.backends.console.EmailBackend'


def parse_database_url(database_url: str) -> dict:
    parsed = urlparse(database_url)
    scheme = parsed.scheme
    engine_map = {
        'postgres': 'django.db.backends.postgresql',
        'postgresql': 'django.db.backends.postgresql',
        'postgresql_psycopg2': 'django.db.backends.postgresql',
        'sqlite': 'django.db.backends.sqlite3',
        'mysql': 'django.db.backends.mysql',
    }

    if scheme == 'sqlite':
        db_path = parsed.path.lstrip('/') or 'db.sqlite3'
        return {
            'ENGINE': engine_map['sqlite'],
            'NAME': str(BASE_DIR / db_path),
        }

    db_config = {
        'ENGINE': engine_map.get(scheme, 'django.db.backends.postgresql'),
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ''),
    }

    sslmode = os.getenv('DB_SSLMODE')
    if sslmode:
        db_config['OPTIONS'] = {'sslmode': sslmode}

    return db_config


def parse_csv_env(value: str, default_values=None) -> list[str]:
    defaults = list(default_values or [])
    parsed_values = []
    seen = set()

    for candidate in defaults + [item.strip() for item in (value or '').split(',') if item.strip()]:
        if not candidate or candidate in seen:
            continue
        parsed_values.append(candidate)
        seen.add(candidate)

    return parsed_values


for env_file in (BASE_DIR / '.env', BASE_DIR / '.env.local'):
    load_environment_file(env_file)


# Quick-start development settings - unsuitable for production
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-placeholder')
DEBUG = get_bool_env('DEBUG', False)

ALLOWED_HOSTS = parse_csv_env(
    os.getenv('ALLOWED_HOSTS', ''),
    default_values=['localhost', '127.0.0.1', '0.0.0.0', '::1', 'testserver', '*.up.railway.app'],
)

default_trusted_origins = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://0.0.0.0:3000',
    'http://0.0.0.0:5173',
    'https://localhost:3000',
    'https://127.0.0.1:3000',
    'https://localhost:5173',
    'https://127.0.0.1:5173',
    'https://*.up.railway.app',
    'http://*.up.railway.app',
]
CSRF_TRUSTED_ORIGINS = parse_csv_env(os.getenv('CSRF_TRUSTED_ORIGINS', ''), default_values=default_trusted_origins)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = 'static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DATABASE_URL = os.getenv('DATABASE_URL')
DATABASES = {
    'default': parse_database_url(DATABASE_URL)
    if DATABASE_URL
    else {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

AUTH_USER_MODEL = 'store.User'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTHENTICATION_BACKENDS = ['store.authentication.EmailOrPhoneBackend']


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Media
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp-relay.brevo.com').strip() or 'smtp-relay.brevo.com'
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = get_bool_env('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = get_bool_env('EMAIL_USE_SSL', False)
# Keep SMTP connection attempts below Gunicorn's default 30-second worker
# timeout.  A healthy Brevo SMTP connection is established in a few seconds;
# a longer timeout only causes the request worker to be killed when port 587
# is blocked by the hosting network.
EMAIL_TIMEOUT = min(max(int(os.getenv('EMAIL_TIMEOUT', '10')), 1), 10)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '').strip()
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@growsalon.com').strip()
# Railway cannot always open outbound SMTP connections.  When this separate
# API key is configured, email is sent through Brevo's HTTPS API instead of
# SMTP, using the normal HTTPS port (443).
BREVO_API_KEY = os.getenv('BREVO_API_KEY', '').strip()
BREVO_API_URL = os.getenv('BREVO_API_URL', 'https://api.brevo.com/v3/smtp/email').strip()
BREVO_API_TIMEOUT = min(max(int(os.getenv('BREVO_API_TIMEOUT', '10')), 1), 10)
VAPID_PUBLIC_KEY = (os.getenv('VAPID_PUBLIC_KEY') or os.getenv('VITE_VAPID_PUBLIC_KEY') or '').strip()
VAPID_PRIVATE_KEY = (os.getenv('VAPID_PRIVATE_KEY') or '').strip()
APP_URL = os.getenv('APP_URL', 'http://localhost:3000').strip() or 'http://localhost:3000'
FRONTEND_URL = os.getenv('FRONTEND_URL', APP_URL).strip() or APP_URL

placeholder_values = {
    'replace_with_brevo_smtp_user',
    'replace_with_brevo_smtp_password',
    'your_brevo_smtp_user',
    'your_brevo_smtp_password',
    'your_verified_sender@example.com',
    'noreply@growsalon.com',
}
if (
    not EMAIL_HOST_USER
    or not EMAIL_HOST_PASSWORD
    or not DEFAULT_FROM_EMAIL
    or EMAIL_HOST_USER.lower() in {value.lower() for value in placeholder_values}
    or EMAIL_HOST_PASSWORD.lower() in {value.lower() for value in placeholder_values}
):
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = resolve_email_backend()

SERVER_EMAIL = DEFAULT_FROM_EMAIL
ORDER_TRACKING_BASE_URL = os.getenv('ORDER_TRACKING_BASE_URL', 'http://127.0.0.1:8000/track')
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')


# REST framework and JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'store.jwt_authentication.CookieJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# CORS and cookie configuration
default_cors_origins = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://0.0.0.0:3000',
    'http://0.0.0.0:5173',
    'https://frontend-production-ae5e.up.railway.app',
    'https://backends-production-3d0b.up.railway.app',
    'https://*.up.railway.app',
    'http://*.up.railway.app',
]
CORS_ALLOWED_ORIGINS = parse_csv_env(os.getenv('CORS_ALLOWED_ORIGINS', ''), default_values=default_cors_origins)
CORS_ALLOWED_ORIGIN_REGEXES = [r'https://.*\.up\.railway\.app', r'http://.*\.up\.railway\.app']

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Cookie settings when using cookies for auth
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = get_bool_env('SESSION_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_SAMESITE = 'None'

CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = get_bool_env('CSRF_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SAMESITE = 'None'


# Staticfiles finders / storage already set above


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
